version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - ollama
    environment:
        - OLLAMA_URL=http://ollama:11434
        - ARCHITECT_AGENT_ANALYSIS_MODEL=llama3.2:3b
        - ARCHITECT_AGENT_GENERATION_MODEL=llama3.2:3b
        - CODER_AGENT_CODING_MODEL=deepseek-coder:6.7b

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data:
    driver: local
    driver_opts:
      type: none
      device: ./data/ollama
      o: bind